[package]
name = "markdown-to-html-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html-node = "0.5.0"
html-node-macro = "0.5.0"
#html-macro = "0.2.2"
minimad = "0.13.0"
